# Generated by Django 5.0.4 on 2024-05-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('time_slot', models.DateTimeField(max_length=100)),
                ('number_of_pets', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
            ],
        ),
    ]
