<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-05-23 00:13
=======
# Generated by Django 5.0.4 on 2024-05-22 04:51
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_booking_date_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=50),
        ),
    ]
